spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j1908?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 980406
mybatis:
  mapper-locations: classpath:mapper/*.xml